### ISSUE TITLE
nonceの生成を一般的なものにして全部統一する？

### ISSUE THREAD

**Issue by him0** [him0/kaesen#10]
# WHAT

nonceの生成を一般的なものにして全部統一する
# WHY
- 現在の仕様では，定期的にAPI KEYを更新しなければならない
  - OSSとして公開するライブラリとしてよろしくない
  - 好きな仕様がしたい場合は，モンキーパッチ推奨ということで良さそう

**Comment by him0** [comment]
@tetsuo-jp @himerumeru コメント下さいー

**Comment by tetsuo-jp** [comment]
> 現在の仕様では，定期的にAPI KEYを更新しなければならない

これはZaifだけでしょうか。

そうならば、クラスMarketに一般的なメソッドget_nonceを書いて、その継承クラスZaifでのみオーバーライドしてはどうでしょうか。

**Comment by him0** [comment]
> クラスMarketに一般的なメソッドget_nonceを書いて

まさにこれがしたくて
一般的なメソッドは，ミリセカンドを使わない実装にしたいと考えています．

Zaifも含めすべての取引所からミリセカンドを使う実装を廃止して
Market#get_nonceに統一しようと思っています．

Zaifだけ今ミリセカンドを使う実装になっていないのは，どんな経緯か忘れました

> Zaifでのみオーバーライド

これはなぜでしょうか

**Comment by tetsuo-jp** [comment]
Zaifだけnonceの桁数が少なくて、1 ms を最小桁にするとオーバーフローしたことがあったと思います。

Zaif 以外を 10 ms、Zaifだけ 1 s を用いるのはどうでしょうか。

**Comment by him0** [comment]
> Zaifだけnonceの桁数が少なくて、1 ms を最小桁にするとオーバーフローしたことがあったと思います。
> Zaif 以外を 10 ms、Zaifだけ 1 s を用いるのはどうでしょうか。

確かにオーバーフローは回避できますが，各取引所が出している実装は，unix時間をnonceにしている実装なので，そちらに揃えたほうが，より一般的で，今後の仕様変更にも強いのではないかと考えています．

nonceをミリセカンドでやりたい人は，get_nonceをオーバーライドすることができるので，今の実装がどうしても必要な場合はそうしてもらえればいいのかなというのを考えています．
- 取引の速度を優先し，Zaif 以外を 10 ms、Zaifだけ 1 sでnonceを生成する 
- 今後の安定性を加味してすべて1 sでnonceを生成する

多分，1 sで生成するメリットがここまでの書き込みで明確に示せていなかったので，これでやっと意義のある議論ができるのではないかと考えています．コメントよろしくお願いします．

**Comment by tetsuo-jp** [comment]
WHAT で示された統一には賛成なのだけど， nonce の最小単位を 1 s にするのが一般的でより有効かがよく分からないです。

> 現在の仕様では，定期的にAPI KEYを更新しなければならない

が指摘しているのは「われわれの現在の実装では，取引 API による認証に用いる nonce が約3ヶ月おきにオーバーフローする問題がある。オーバーフローが起きると以降の認証に失敗する問題がある。」ということでしょうか。また，これはZaifのみの問題でしょうか。一部の取引所の問題ならば，そういった取引所のクラスのみメソッドをオーバーライドすれば良いように思います。

> 各取引所が出している実装は，unix時間をnonceにしている実装なので，そちらに揃えたほうが，より一般的で，今後の仕様変更にも強いのではないかと考えています．

今でも「unix時間をnonceにしている実装」なのでは。
それとも単位が問題と言うことでしょうか。BitFlyer や bitfinex は ms 単位の例（`Date.now().toString()`）が示されていて，Zaifは示されておらず，Quoineは乱数の例 `nonce = SecureRandom.hex` ですね。
https://lightning.bitflyer.jp/docs?lang=ja
http://docs.bitfinex.com/#rest
https://corp.zaif.jp/api-docs/
https://developers.quoine.com/#introduction
各取引所の nonce の最大値も考慮すると，Zaif以外は ms 単位の nonce を用いても実際上オーバーフローしないのではないでしょうか。

一緒に議論した方がいい関連問題なのですが，同じ nonce を使用したときインクリメントしてずらす方法は副次的な問題がないでしょうか？たとえば，nonce を 1 s 単位にして，1 s 間に200回 private API たたくと200秒未来まで nonce を先取りして使用してしまう問題があるように思います。

**Comment by him0** [comment]
> BitFlyer や bitfinex は ms 単位の例（Date.now().toString()）が示されていて...

[BitflyerのAPI Playgroud](https://lightning.bitflyer.jp/docs/playground)
- Rubyの項目 `Time.now.to_i.to_s` 1 s単位
- Javascriptの項目 `Date.now().toString()`  1 ms単位
- Perlの項目 `time` 1 s単位
- C#の項目 `TotalSeconds` 1 s単位

なぜかjsだけms

[bitfinexのRubyのライブラリ](https://github.com/bitfinexcom/bitfinex-api-rb/blob/master/lib/bitfinex/authenticated_rest.rb)
- `payload['nonce'] = (Time.now.to_f * 10_000).to_i.to_s` 1/10 ms単位

Rubyのライブラリばかり注目していましたが言語ごとに実装にかなりばらつきがあるようですね。Rubyの実装から1 s単位の利用を一般的と判断したのは，自分のミスリードだったみたいです。提案通りms単位でnonceを生成する実装が良いと思います。

> 一部の取引所の問題ならば，そういった取引所のクラスのみメソッドをオーバーライドすれば良いように思います。
> 
> 各取引所の nonce の最大値も考慮すると，Zaif以外は ms 単位の nonce を用いても実際上オーバーフローしないのではないでしょうか。

現在オーバーフローを確認できている取引所は，Zaifだけであり，一部の取引所の問題として，処理しても良いのでは，という意見には賛成です。基本的にMarket#get_nonceで1 msを基準にnonceを生成し利用，Zaifについては，オーバーライドして対応という形で行きたいと思います。

## 残りの議論項目
- [x] Zaif#get_nonceの生成規則
- [ ] nonceのインクリメントによる未来のnonce先取り問題

ms単位でのnonce生成をすれば，nonceをインクリメント実装は必要ないというのも一つの選択肢と考えています。

**Comment by him0** [comment]
zaif ミリ秒対応したので close しまーす
