### ISSUE TITLE
オーダーをキャンセルできるようにする

### ISSUE THREAD

**Issue by him0** [him0/kaesen#11]
# WHAT
- 各市場でオーダーのIDを指定し，キャンセルできるようにする
# WHY
- キャンセルできないのは辛いから

**Comment by him0** [comment]
取引所と実装状況
- [x] bitFlyer
- [x] BtcBox
- [x] coincheck
- [x] Zaif

#13 でZaifはやった。

**Comment by him0** [comment]
bitflyer でオーダーキャンセルできないんだけどというクレームが来た
API の方はあるのに未実装なのは，そろそろ辛い感じなので，やっていく気持ちをそろそろ持たなければ

**Comment by fukukun** [comment]
bitFlyer・coincheckオーダーキャンセルできそうですか？

**Comment by him0** [comment]
0.2.0 としてリリースします．

**Comment by him0** [comment]
0.2.0としてリリースします．
