### ISSUE TITLE
キーの取り扱い、環境変数にするのはおせっかい

### ISSUE THREAD

**Issue by him0** [him0/kaesen#17]
キーの取り扱い、環境変数にするのはおせっかいでないかという議論がしたいです。

クライアント初期化するときに必要に応じて、入力してもらうのほうが利便性が高い気がしてきました。

Zaifのnonceの仕様直しているときに、思いました。

**Comment by him0** [comment]
https://github.com/sferik/twitter/blob/master/lib/twitter/client.rb#L11-L20

この実装良さそう

**Comment by tetsuo-jp** [comment]
引数でキーを渡す方が、参照透過性の点では良いと思います。利便性はどちらとも言えない気がします。kaesenを使う側で環境変数を使うのは少しの修正でできると思います。

**Comment by him0** [comment]
やった
